# First stage
FROM node:14.18.1-alpine as builder

# Install dependencies for node-gyp
RUN apk update && apk add python3 make g++ && rm -rf /var/cache/apk/*

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# Second stage
FROM node:14.18.1-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

CMD ["yarn", "run", "develop"]
