# Install dependencies only when needed
FROM node:14.18.1-alpine as builder

# Install dependencies for node-gyp
RUN apk update && apk add python3 make g++ && rm -rf /var/cache/apk/*

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

# Copy all the files and run next
FROM node:14.18.1-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

CMD ["npm", "run", "develop"]
