FROM nginx:stable-alpine

EXPOSE 80

COPY ./production/upstream.conf /etc/nginx/conf.d/upstream.conf
COPY ./production/website-server.conf /etc/nginx/sites-enabled/rozhdestvo-youth.by
COPY ./production/admin-server.conf /etc/nginx/sites-enabled/admin.rozhdestvo-youth.by
